spring:
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:54321/db_organization
    username: user
    password: 1234
    driver-class-name: org.postgresql.Driver

server:
  port: 8082